# Generated by Django 3.2.24 on 2024-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnerName', models.CharField(max_length=100)),
                ('organizationType', models.CharField(choices=[('Consultative Partnerships', 'Consultative Partnerships'), ('Contributory Partnerships', 'Contributory Partnerships'), ('Operational Partnerships', 'Operational Partnerships'), ('Collaborative Partnerships', 'Collaborative Partnerships')], max_length=50)),
                ('availableResources', models.CharField(choices=[('Financial Resources', 'Financial Resources'), ('Physical Resources', 'Physical Resources'), ('Human Capital', 'Human Capital'), ('Networking Resources', 'Networking Resources'), ('Educational Resources', 'Educational Resources'), ('Technology Resources', 'Technology Resources'), ('Marketing & Promotion Resources', 'Marketing and Promotion Resources'), ('Community Engagement Resources', 'Community Engagement Resources')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
