# Generated by Django 3.2.24 on 2024-03-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='availableResources',
            new_name='available_Resources',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='organizationType',
            new_name='organization_Type',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='partnerName',
            new_name='partner_Name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='phoneNumber',
            new_name='phone_Number',
        ),
    ]
