# Generated by Django 3.2.24 on 2024-03-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20240309_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='available_Resources',
            field=models.CharField(choices=[('Financial Resources', 'Financial Resources'), ('Physical Resources', 'Physical Resources'), ('Human Capital', 'Human Capital'), ('Networking Resources', 'Networking Resources'), ('Educational Resources', 'Educational Resources'), ('Technology Resources', 'Technology Resources'), ('Marketing and Promotion Resources', 'Marketing and Promotion Resources'), ('Community Engagement Resources', 'Community Engagement Resources')], max_length=50),
        ),
    ]
